### ISSUE TITLE
[Suggestion] Iframe Render in Editor

### ISSUE THREAD

**Issue by gth001** [ozntel/oz-image-in-editor-obsidian#14]

**Comment by ozntel** [comment]
Hi @gth001, Can you clarify further what you want to be rendered in an iframe?

**Comment by gth001** [comment]
Oh I meant your plugin will render image and PDF in editor mode. It would also be cool to add iframe.

**Comment by ozntel** [comment]
Sorry, I didn't understand. Do you want HTML element to be rendered in editor directly? Can you explain on an example?

**Comment by gth001** [comment]
**Currently:**
With no plugins, we see: ![](image.png)
With Oz plugin, we see the image. It is as if we were in Preview mode, yet we are in edit mode.

**My wish:**
With no plugins, we see: <iframe src="google.com">
With Oz plugin, we see the iframe. It is as if we were in Preview mode, yet we are in edit mode.

**Comment by ozntel** [comment]
Ok, so I understand correctly that you would like an HTML tag to be rendered in the Markdown editor. 
Actually, the primary purpose of the plugin is to render Markdown syntax but I will see what I can do in the future and if other users also find this feature useful.
In case I implement such a feature, I think it would be better to render all HTML tags rather than rendering only iframe tag.
Thanks for the suggestion

**Comment by ozntel** [comment]
Hi @gth001, I just pushed a new `main.js` file, which renders `iframe` nodes. Before I release a new update, could you please try and let me know if it works properly for you?

**Comment by gth001** [comment]
Wow, cool, look at that! It works perfectly for me :)

The only small note I have is that in settings, "iframe-s" should be "iframes" and "PDF-s" should be "PDFs" since the plural grammar doesn't need any punctuation.

**Comment by ozntel** [comment]
I am happy to hear that the plugin is helpful.
Just released the version including `iframe` rendering. You can update from Obsidian community plugins.
I corrected the plural names as you suggested :)
