### ISSUE TITLE
Excalidraw

### ISSUE THREAD

**Issue by zsviczian** [ozntel/oz-image-in-editor-obsidian#15]
Hi Ozan, I love your image-in-editor plugin!

I will be rolling out a change to Excalidraw in one or two days. I finally figured out how to handle native embedding i.e. `![[mydrawing.excalidraw]]`. I will be departing the current codeblock approach.

This opens up the opportunity to use your approach for Excalidraw drawings as well.

I actually implemented your editor approach into Excalidraw... but on second thought I think it would make more sense to have it integrated into your plugin. It is a very simple to make it happen.

You can check for `.excalidraw` file extension and add a code similar to this:
```js
if (pp.plugins.getPlugin("obsidian-excalidraw-plugin") {
  const filePath = app.metadataCache.getFirstLinkpathDest(decodeURIComponent(filename), sourcePath);
  ExcalidrawAutomate.reset();
  const svg = await ExcalidrawAutomate.createSVG(filePath);
  cm.addLineWidget(line_number, svg, { className: 'oz-image-widget' });
  /* or
  const img = await ExcalidarwAutomate.createPNG(filePath);
  cm.addLineWidget(line_number, svg, { className: 'oz-image-widget' });
 */
```

This should do the trick.
More info about the function here: https://github.com/zsviczian/obsidian-excalidraw-plugin/blob/e472dbebb259023fc656a556e51d16788818dd5e/src/ExcalidrawTemplate.ts#L188

**Comment by ozntel** [comment]
Hi @zsviczian In comparison to your plugin, mine is only a small trick, thank you also for your great plugin  🙂 

I would be more than happy to implement the approach you mentioned above.

Just a small question, could you advise maybe how I can use a function from your plugin (`ExcalidrawAutomate.createSVG`) to ensure that I convert drawings into PNG/SVG?

Also, would you prefer rendering `excalidraw` drawings as default as long as they have the plugin installed or should we give an option for users within the settings?

**Comment by zsviczian** [comment]
ExcalidrawAutomate is published to the window object, and is available without any issues.
Try it... open console log and type ExcalidrawAutomate. You should see the object.

You probably need to add `// @ts-ignore` the line above.

I wouldn't bother with a separate setting, unless people ask for it specifically.

Note I added one line to the code above, it is worth calling ExcalidrawAutomate.reset() as a first step.

**Comment by ozntel** [comment]
Yes, you are right. The object is visible.

I just included the rendering option for excalidraw drawings, you can see the corresponding part below:

https://github.com/ozntel/oz-image-in-editor-obsidian/blob/34edb13206fa93c55d1cab28afa0d1c6ff679f63/src/check-line.ts#L109

It renders the image properly now (You can try with the new `main.js` I have in the repo) The only thing people might be complaining about is that the image is refreshed for all changes in the line since each change generates a new URL for the blob object.  I don't know if it is possible but I will try to compare `stat.mtime` each time to ensure that the image doesn't have a new URL as long as the initial `mtime` hasn't changed. I am not that master, maybe you have an idea how to keep a state object in the plugin?

**Comment by zsviczian** [comment]
Great! I will test it tonight!
I was looking at your code... to see if I could make it work on a mobile as well. 
The desktop app still has CodeMirror 5, mobiles already use CodeMirror 6. Some of the functions you are using are deprecated and thus in-editor-images don't work on Obsidian Mobile. 
I had couple questions on this on OMG.

https://discord.com/channels/686053708261228577/840286264964022302/844272747609980998
https://discord.com/channels/686053708261228577/840286264964022302/844279002260963380
https://discord.com/channels/686053708261228577/840286264964022302/844355683959701505
https://discord.com/channels/686053708261228577/840286264964022302/844360227679371314 
https://discord.com/channels/824179057620811806/833711930886586428/844285882273890314

**Comment by ozntel** [comment]
Yes, to be honest, I have been in search for a while to find a way to make the plugin work in the mobile app.
Unfortunately, the new Editor type has a very limited API at the moment. I can not get to the widget in CM6 as they have in their documentation:

https://codemirror.net/6/docs/ref/#view.Decoration^widget

If only we have a way to get to the widget as we do right now with `addLineWidget`, I can definitely change the way of working in the plugin to ensure we can support mobile, as well

**Comment by zsviczian** [comment]
Did you try raising the question on OMG with Licat?

**Comment by ozntel** [comment]
I just asked actually in the group and found out that widgets are not supported yet, however, it is in the roadmap: 
https://discord.com/channels/686053708261228577/840286264964022302/844557460831862814

This is Licat's response:
https://discord.com/channels/686053708261228577/840286264964022302/842454385288151101

For the image preview in the mobile editor, I suppose we need to wait for a while.

**Comment by zsviczian** [comment]
Hi, I tested main.js. Overall it works as advertised. Thank you!

It is not perfect, sometimes the image appeared twice temporarily, sometimes the formatting did not work... I guess generating the image takes up lot of resources and a few change events were missed, or there was some other race condition in the code, because in developer tools I saw that the alt attribute for the img was incomplete e.g. "#x-sma".

I have two suggestions if you don't mind my input:
1. I recommend using the standard Obsidian image sizing as described in [Obsidian help](https://help.obsidian.md/How+to/Embed+files#Resize+images);  i.e. `![[image.png|300x200]]` or `![[image.png|300]]`. The #x-small, #xx-small notation has no effect in preview mode.
2. I don't think real time update is necessary. Updating the image after the user has navigated away from the line would be perfectly sufficient. I would implement two event handlers: `on("change"` and `on("beforeChange"`. When the line is different between change and before change, then I would execute your script on the line the user has just left. This would solve the flicker, and drastically reduce the resource impact of in-editor-images.

Thanks once more for incorporating Excalidraw in your awesome plugin! in-editor-images is a life saver for me!

**Comment by ozntel** [comment]
> I guess generating the image takes up lot of resources and a few change events were missed

I don't think it is because generating the image takes up a lot of resources. The image is refreshed in DOM with a new link after each change, which causes flickering in the screen since it thinks that it is totally new image. I just found a way, which actually helps to solve flickering issue for excalidraw drawings:

https://github.com/ozntel/oz-image-in-editor-obsidian/blob/9286e29300deaa6007d1c21e70e17c8c0773703e/src/check-line.ts#L111

It basically adds a key pair of `mtime` and  `alt` as an attribute and checks each time if it changed. As long as the original `excalidraw` file or `alt` attributes don't change, the image shouldn't be refreshed.

> I recommend using the standard Obsidian image sizing as described in Obsidian help; i.e. ![[image.png|300x200]] or ![[image.png|300]]. The #x-small, #xx-small notation has no effect in preview mode.

Since there are a lot of users using `#x-small` format right now, I would rather not eliminate the existing format but implement an additional function for the alt text to detect `300x200` format. If so, I can set the height and width directly from the plugin and not leave it for CSS.

> I don't think real time update is necessary. Updating the image after the user has navigated away from the line would be perfectly sufficient. I would implement two event handlers: on("change" and on("beforeChange". When the line is different between change and before change, then I would execute your script on the line the user has just left. This would solve the flicker, and drastically reduce the resource impact of in-editor-images.

Actually `on('change')` is more consuming since it is run for all kinds of changes. I have moved from this approach as per recommendation from `pjeby` and right now the plugin only checks the edited lines.

> I saw that the alt attribute for the img was incomplete e.g. "#x-sma".

Can you give a sample where it was generated in this way so that I can check what causes an issue?

**Comment by zsviczian** [comment]
Thanks.
New main.js seems to work well. 

I got an error when I had two drawings next to each other in the same line `![[Test1.excalidraw|#x-small]]![[Test2.excalidraw|1000]]`:
![image](https://user-images.githubusercontent.com/14358394/118853420-061be100-b8d4-11eb-950f-d747cc3aba25.png)
```js
if (filename.endsWith('excalidraw')) {
                // The file is an excalidraw drawing
                // @ts-ignore
                if (app.plugins.getPlugin('obsidian-excalidraw-plugin')) {
                    var excalidrawFile = app.metadataCache.getFirstLinkpathDest(decodeURIComponent(filename), sourcePath);
                    var mtimeAlt = excalidrawFile.stat.mtime + '-' + alt //<<<< Error was here
                    var loadedDrawing = document.querySelector(`[mtimeAlt='${mtimeAlt}']`);
                    if (loadedDrawing == null) {
                        // @ts-ignore
                        ExcalidrawAutomate.reset();
                        // @ts-ignore
                        image = await ExcalidrawAutomate.createPNG(excalidrawFile.path);
                        img.src = URL.createObjectURL(image);
                        img.setAttr("mtimeAlt", mtimeAlt);
                    } else {
```
Also got an error in console.log when I referenced a non-existent file: `![[non-existentfile.excalidraw]]`


I can't reproduce the x-small error... my PC was really busy with other stuff, and not very reactive at the time, thus I thought it is some performance-related race condition in the code. It is not Excalidraw specific, and I wouldn't worry about it unless others flag it.

**Comment by ozntel** [comment]
> I got an error when I had two drawings next to each other in the same line![[Test1.excalidraw|#x-small]]![[Test2.excalidraw|1000]]:

It was because of greedy regex. I changed to non-greedy. But it will always render the first link provided within the line.

> Also got an error in console.log when I referenced a non-existent file: ![[non-existentfile.excalidraw]]
I included a null check. It should do the job.

Whenever you are happy with the result, I can release the version 🙂 

Later on, I will also work on implementing `alt` text format `300x300` as you suggested.

**Comment by zsviczian** [comment]
Thank you!
This is good!

I hope to release my update still later today. Since this is a bigger change >> I am moving away from using a code block, to embedding using the normal markdown format, I will publish a short video and will mention your plugin as a nice companion for in-edit-image viewing.

**Comment by ozntel** [comment]
Just published the version and included information in the README that they can now view `excalidraw` drawings in the editor. Thanks for the nice collaboration 🙂

**Comment by ozntel** [comment]
Hi @zsviczian I just released a version, which allows users to use `Width x Height` or only `Width` within the alt text for sizing the images. Hope it should do the job 🙂

**Comment by zsviczian** [comment]
Just tried it. Works great! Thanks.
