### ISSUE TITLE
Add command to toggle images in editor

### ISSUE THREAD

**Issue by HEmile** [ozntel/oz-image-in-editor-obsidian#20]
Hi there, loving this plugin. 
Is there any chance you can add a command to toggle the display of images in the editor?

**Comment by ozntel** [comment]
Hi, I am glad the plugin is useful.
If I understand correctly you want toggle to turn on/off the image rendering feature. Since the main purpose of the plugin is to only render images, wouldn't be enough to toggle the plugin itself from the community plugins? I am just afraid it might cause confusion for the active users.

**Comment by HEmile** [comment]
Toggling the plugin from the community plugins cannot be done using hotkeys/the command pallette. I have some notes with many images, and that'd often be annoying to edit in if they're all displayed. Basically you'd just 'pause' the plugin's functionality for a while when you use that command.

**Comment by ozntel** [comment]
I just pushed new `main.js` to the repo with the feature you requested.
Can you download and try if it works for you? Then I can release the new version.

**Comment by ozntel** [comment]
The feature is included in version 1.1.2. Please update the plugin and let me know if you encounter any issue

**Comment by HEmile** [comment]
Thank you, it works well!
