### ISSUE TITLE
Excalidraw drawing appears twice after editing the drawing (in a new pane)

### ISSUE THREAD

**Issue by bwydoogh** [ozntel/oz-image-in-editor-obsidian#24]
**Describe the bug**
Using the plug-in together with "Ozan's Image in Editor" plug-in. When editing a drawing, embedded in a note, in a new pane... the drawing appears 2 times in the note after editing the drawing (and closing the drawing). Editor mode.

**To Reproduce**
1. Open a note which embeds a drawing
2. Open the drawing in a new pane (_pay attention: I am using the "Sliding panes" plug-in_)
3. Edit the drawing
4. Close the drawing 
5. Check the note (in editor mode): the (edited) drawing appears 2 times

**Expected behavior**
The drawing appears once.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS

**Additional context**
Sliding panes plug-in.
Latest version of all plug-ins.

**Comment by ozntel** [comment]
Hi @bwydoogh 

I just followed all of the steps, which you described above, to reproduce the issue (also installed Sliding Panes), but couldn't manage the get 2 drawings in a single line.

Can you maybe try again all the steps to understand under which circumstances this issue is caused? There should be something else, which triggers the issue.

If it behaves exactly the same, we can maybe go into settings details.

**Comment by bwydoogh** [comment]
Hi @ozntel.

Could it be related to the "Refresh Images after Changes"? I disabled all plug-ins except this one and Excalidraw; every single time, after editing the drawing in a new pane the drawing refreshes in the note pane but the drawing appears twice. Did you try with that setting ON?

**Comment by ozntel** [comment]
Yes, the refresh option is turned on when I follow your steps to reproduce the issue. 
Is there a chance you can record the issue? Maybe it might help me to understand where the issue comes from.

**Comment by bwydoogh** [comment]
@ozntel See this recording: https://www.dropbox.com/s/k368q8ezxz9tfwx/Screen%20Recording%202021-05-28%20at%2006.55.55.mov?dl=0

**Comment by ozntel** [comment]
To be honest, I watched like 10 times and repeated exactly the steps you are following and the issue doesn't occur on my computer. 
Let's leave this issue open for the moment and we will see if there is anyone who can produce the same issue for us. 
It will at least help me to understand where the issue comes from and I can focus on the fragment to improve. 
There is evidently something that has an effect on your obsidian or computer, but I couldn't find what.

**Comment by bwydoogh** [comment]
Hi @ozntel; found the issue: it happens when you turn on the "Auto-export PNG" setting in the Excalidraw plug-in. So I will close this issue and go back to the developer of that plug-in. 
Thanks for having a look!
