### ISSUE TITLE
[Feature Request] Allow ![]() external links to render video

### ISSUE THREAD

**Issue by Obadiahcruz** [ozntel/oz-image-in-editor-obsidian#27]
Hello! Amazing new update for iFrames! I have been using media-extended plugin to create timestamps in obsidian but it requires the ![] () for external links. (ignore the space) 

When I saw your update I realized that ![] () is not supported , can this be possible? 

for example: ![elephants] (https://www.youtube.com/watch?v=GyI2fbz9404) 

Thank You so much for allowing iframes for video for editor

**Comment by ozntel** [comment]
Hi @Obadiahcruz, I am glad the plugin is helpful.

Since I use `![]()` format to detect images, PDF Files, excalidraw drawings, etc. from local folders or the internet, it would be challenging to differentiate video and images from each other when it comes to external links. 

However, I will keep your suggestion in mind in case I will find an optimal way to implement it in the future
