### ISSUE TITLE
How do I solve the problem of selecting text in WYSIWYG mode and not being able to position it?

### ISSUE THREAD

**Issue by zhl111** [ozntel/oz-image-in-editor-obsidian#28]

**Comment by ozntel** [comment]
I didn't understand your question, to be honest. Can you explain with an example and include some recording/screenshots so that I can check what the issue is?
Btw WYSIWYG mode only includes additional CSS to the application when you turn on the settings. In case you have anything that doesn't work properly, you can overwrite the styling to ensure it works properly.

**Comment by zhl111** [comment]
sorry。theme：California oast
![动画](https://user-images.githubusercontent.com/29135984/120789976-e7207e80-c564-11eb-8c5c-b2ec3d51761d.gif)

**Comment by Mara-Li** [comment]
Hello!
As I said to Ozan on discord, you can't repear this behavior with CSS.
It's because CodeMirror don't have a select and the active  line  (used in this snippet) is disabled when you select some text.

That's why the cm-formatting disappear. Also, more you have space difference between the two (active and non active) more the hightlight will be difficult to use.
It's specially visible with links.

The only way in CSS, to have a better behavior is to minimize the space between the two mode. For example, in [my snippet](https://github.com/Mara-Li/Obsidian-share/blob/main/snippets/WYSIWYG_stable.css) I totally disabled the rendering of link. 

I dunno if it's possible to force the active line rendering with JS when the text is selected.

---

[source](https://forum.obsidian.md/t/css-active-line-fails-when-highlighting-text/4036)
