### ISSUE TITLE
missing file oz-image-in-editor-obsidian/main.js

### ISSUE THREAD

**Issue by maxpietsch** [ozntel/oz-image-in-editor-obsidian#4]
The plugin fails to load on macos, obsidian 0.11.13. 

Installation:
```
cd <path to notebook>/.obsidian/plugins
git clone git@github.com:ozntel/oz-image-in-editor-obsidian.git
```

Activation:
<img width="1372" alt="Screenshot 2021-04-28 at 12 29 46" src="https://user-images.githubusercontent.com/10046944/116390089-fc93e180-a81d-11eb-8565-9e8547fab251.png">

The obisian developer console states:

`Plugin failure: oz-image-plugin Error: ENOENT: no such file or directory, open '<path to notebook>/.obsidian/plugins/oz-image-in-editor-obsidian/main.js'`

**Comment by ozntel** [comment]
Hi @maxpietsch, 
The plugin is still under development. To be able to work efficiently with the Obsidian team, I removed the `.js` file from the repo as per their request.   
There are going to be a few changes to make the plugin more efficient, however, if you want as a temporary solution, you can download `oz-image-in-editor-obsidian.zip` from  https://github.com/ozntel/oz-image-in-editor-obsidian/releases and extract it into `/.obsidian/plugins/`. 
But please follow the plugin since I will release the new `.js` file very soon.

**Comment by maxpietsch** [comment]
Thanks, works for me now! Very much appreciate your plugin!
