### ISSUE TITLE
preview plug-in

### ISSUE THREAD

**Issue by AntonioDEM** [ozntel/oz-image-in-editor-obsidian#48]
could you add these lines in the plugin? for preview

```
div.markdown-preview-view img[alt$="#small"] {
  width: max(200px,75%);
  max-height:auto;
  outline: none;
  cursor: zoom-in;
}

div.markdown-preview-view img[alt$="x-small"] {
  width: max(100px,50%);
  max-height:auto;
  outline: none;
  cursor: zoom-in;
}

div.markdown-preview-view img[alt$="xx-small"] {
  width: max(50px,25%);
  max-height:auto;
  outline: none;
  cursor: zoom-in;
}
```

**Comment by ozntel** [comment]
Since the main purpose of the plugin is to add image previews in the editor, I wouldn't like to interfere with the preview mode. I would suggest adding them in your custom CSS. Or you can use as below:
Width x Height: ![100x100](image.png)
Width: ![300](image.png)
This is common in both preview mode and in my plugin. There wouldn't be any additional CSS required.
