### ISSUE TITLE
when image have been added in code blocks, it will be rendered.

### ISSUE THREAD

**Issue by renmu123** [ozntel/oz-image-in-editor-obsidian#6]
![image](https://user-images.githubusercontent.com/26896790/116782611-cb850c80-aabc-11eb-854f-bf7e8d12ba24.png)

l think it should be not rendered in code blocks
If someone depends the feature, a switch can be added to crontrol this action.

**Comment by ozntel** [comment]
Hi @renmu123, to be honest, it didn't come to my mind that someone would add an image in a code block :)
I searched for some options but it is quite hard to get line classes for the moment.
As a temporary solution, you can add the following CSS so that it is not visible within your code blocks even though you will have the widget in your DOM:
```
pre.HyperMD-codeblock + div.oz-image-widget {
  display: none !important;
}
```
Hope this helps.

**Comment by renmu123** [comment]
thanks
