### ISSUE TITLE
Realtime updating head preview and block preview 

### ISSUE THREAD

**Issue by Connor-yang96** [ozntel/oz-image-in-editor-obsidian#69]
![HCgnR4g0mc](https://user-images.githubusercontent.com/81000027/132195132-108ef771-553c-454d-9b89-8a91f8c056cd.gif)

**Comment by ozntel** [comment]
Editor is a little bit different than the pure HTML or preview mode. Each refresh will cause your cursor to move somewhere else or even scroll up a little since it needs to remove all widget and add from scratch.  That's the reason why updating the rendered blocks wouldn't be ideal for user experience and I removed specifically. Hope this helps.
