### ISSUE TITLE
feature request: render transclusions for whole pages

### ISSUE THREAD

**Issue by derekvan** [ozntel/oz-image-in-editor-obsidian#70]
Some of my notes are very "atomic" and I would love to see them rendered in the editor view in the same way this plugin works with header and block ref transclusions. Any chance that could be added here? Thanks!

**Comment by lowlight-ua** [comment]
Thanks to this issue I realized that entire-page transclusion rendering is simply not supported. I was wondering what I was doing wrong.

Seconding the request.

**Comment by ozntel** [comment]
It is now available in the last release. You need to be an insider for the moment to be able update the plugin and use this feature since some of the new features rely on `0.12.16` version of Obsidian. For the details, you can check the message in Discord:

https://discord.com/channels/686053708261228577/855181471643861002/896684880749035560
