### ISSUE TITLE
BUG - Image catch

### ISSUE THREAD

**Issue by b1uegh0st** [ozntel/oz-image-in-editor-obsidian#9]
Hi, thanks for the plug-in.

 I find one problem while using: The image I pasted to notes, when rendered in editor mode, cannot be refreshed when it changed.

 Steps:
 - Add one image to notes in editor.
 - Change it (using other programs). Save.
 - The picture in editor view don't change. When switch to preview, can see the new [version] but when switch back to editor, still [old version[.
 - Try delete some text in the embedded `![[xxx]]` then change it back to "refresh" but still the old image.
 - Can only change by re-launch Obsidian.

Thanks,
NA

**Comment by b1uegh0st** [comment]
Extra case:
- Can also "refresh" by closing the notes and re-open again.

Extra info:
- I am using Excalidraw plug-in for Obsidian, so side-by-side update will be neat. I imagine other might not care as much about this issue.

**Comment by ozntel** [comment]
Hi @b1uegh0st 

I just released a version, which should solve partially your problem. The image is now loaded exactly as it is loaded in the Preview mode. 

It is theoretically possible to force the image to load again once the original file is changed, however, it will create an extra weight for the user's computer and I think it would be overkill for the plugin.

I have 3 types of triggers to load the image: 

1. Vault to be loaded (checks all open files)
2. Markdown file to be opened (checks only the opened file)
3. Line text to be changed (checks only the line-edited)

Hence, you don't need to exit from the note, but just click space after the image so that line is checked again for a new image view.

Hope this helps

**Comment by b1uegh0st** [comment]
Cool, many thanks. I think the 3rd solution is good enough!

**Comment by joihn** [comment]
thanks for this tool
I wish I could have an an "Image autorefresh" when the image file changes 
I often use an external tool for image annotation, I wish the modification would pop
